/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Excepciones.AceleradoInvalidoException;
import Excepciones.ApagadoInvalidoExcepcion;
import Excepciones.EncendidoInvalidoExcepcion;
import Excepciones.FrenadoBruscoInvalidoException;
import Excepciones.FrenadoInvalidoException;
import Excepciones.LlantasInvalidasException;
import Excepciones.MotorInvalidoException;
import Excepciones.VehiculoAccidentadoException;
import Excepciones.VehiculoPantiandoException;
import Modelos.Actualizable;
import Modelos.Vehiculo;
import java.awt.List;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Andres Esparza
 */
public class VistaPrincipal extends javax.swing.JFrame implements Actualizable{

    private Vehiculo vehiculo;
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bFrenar = new javax.swing.JButton();
        bAcelerar = new javax.swing.JButton();
        tfValorMovimiento = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        bApagar = new javax.swing.JButton();
        bEncender = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lVelocidadActual = new javax.swing.JLabel();
        lEstadoMotor = new javax.swing.JLabel();
        lEstadoViaje = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMensaje = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        bFrenar.setText("Frenar");
        bFrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFrenarActionPerformed(evt);
            }
        });

        bAcelerar.setText("Acelerar");
        bAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcelerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfValorMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAcelerar)
                .addGap(18, 18, 18)
                .addComponent(bFrenar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfValorMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        bApagar.setText("Apagar");
        bApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bApagarActionPerformed(evt);
            }
        });

        bEncender.setText("Encender");
        bEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEncenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bApagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEncender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bEncender)
                .addGap(18, 18, 18)
                .addComponent(bApagar)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        lVelocidadActual.setText("0,0Km/h");

        lEstadoMotor.setText("Apagado");

        lEstadoViaje.setText("Detenido");

        jLabel1.setText("Velocidad Actual:");

        jLabel2.setText("Estado Motor:");

        jLabel3.setText("Estado de Viaje:");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        taMensaje.setEditable(false);
        taMensaje.setColumns(20);
        taMensaje.setLineWrap(true);
        taMensaje.setRows(5);
        jScrollPane1.setViewportView(taMensaje);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel2)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lVelocidadActual)
                                .addGap(148, 148, 148)
                                .addComponent(lEstadoMotor)
                                .addGap(137, 137, 137)
                                .addComponent(lEstadoViaje)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lVelocidadActual)
                    .addComponent(lEstadoMotor)
                    .addComponent(lEstadoViaje))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcelerarActionPerformed
        String valorAceleracion = tfValorMovimiento.getText();
        try{
            int velocidad = Integer.parseInt(valorAceleracion.trim());
            vehiculo.acelerar(velocidad);
        }
        catch(java.lang.NumberFormatException e){
            manejarExcepciones("Eso no es un numero valido");
        } catch (AceleradoInvalidoException e) {
            manejarExcepciones(e);
        } catch (VehiculoAccidentadoException e) {
            manejarExcepciones(e);
        } 
    }//GEN-LAST:event_bAcelerarActionPerformed

    private void bFrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFrenarActionPerformed
        String valorFrenado = tfValorMovimiento.getText();
        try{
            int velocidad = Integer.parseInt(valorFrenado.trim());
            vehiculo.frenar(velocidad*(-1));
        }
        catch(java.lang.NumberFormatException e){
            manejarExcepciones("Eso no es un numero");
        } catch (FrenadoInvalidoException e) {
            manejarExcepciones(e);
        } catch (VehiculoPantiandoException e) {
            manejarExcepciones(e);
        } catch (FrenadoBruscoInvalidoException e) {
            manejarExcepciones(e);
        } 
    }//GEN-LAST:event_bFrenarActionPerformed

    private void bEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEncenderActionPerformed
        try {
            vehiculo.encender();
        } catch (EncendidoInvalidoExcepcion e) {
            manejarExcepciones(e);
        }
        this.actualizarLabels();
    }//GEN-LAST:event_bEncenderActionPerformed

    private void bApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bApagarActionPerformed
        try {
            vehiculo.apagar();
        } catch (ApagadoInvalidoExcepcion e) {
            manejarExcepciones(e);
        } catch (VehiculoAccidentadoException e) {
            manejarExcepciones(e);
        }
        this.actualizarLabels();
    }//GEN-LAST:event_bApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        VistaPrincipal vista = new VistaPrincipal();
        Vehiculo vehiculo = new Vehiculo();
        RandomAccessFile lector;
        try {
            lector = new RandomAccessFile("src/Datos/datos.txt","r");
            String linea = "";
            String textoCompleto = "";
            while((linea = lector.readLine()) != null){
                textoCompleto = textoCompleto + linea+"\n"; 
            }
            lector.close();
            String [] nuevoTexto = textoCompleto.split("\n");
            String [] llantas = nuevoTexto[0].split(" ");
            String [] motor = nuevoTexto[1].split(" ");
            vehiculo.addComponents(llantas, motor);
        } catch (FileNotFoundException ex) {
            vista.manejarExcepciones("No se encontro el archivo con los datos");
        } catch (IOException ex) {
            vista.manejarExcepciones("Se ha producido un error a la hora de intentar manejar el archivo");
        } catch (LlantasInvalidasException ex) {
            vista.manejarExcepciones(ex);
        } catch (MotorInvalidoException ex) {
            vista.manejarExcepciones(ex);
        } 
        vista.setVehiculo(vehiculo);
        vehiculo.setActualizable(vista);
        vista.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAcelerar;
    private javax.swing.JButton bApagar;
    private javax.swing.JButton bEncender;
    private javax.swing.JButton bFrenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lEstadoMotor;
    private javax.swing.JLabel lEstadoViaje;
    private javax.swing.JLabel lVelocidadActual;
    private javax.swing.JTextArea taMensaje;
    private javax.swing.JTextField tfValorMovimiento;
    // End of variables declaration//GEN-END:variables

    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    
    public void actualizarLabels(){
        lVelocidadActual.setText(""+vehiculo.getVelocidadActual()+"Km/h");
        System.out.println(""+vehiculo.getVelocidadActual());
        if(vehiculo.getEstadoMotor()== Vehiculo.ESTADO_MOTOR_ENCENDIDO){
            lEstadoMotor.setText("Encendido");
        }else{
            lEstadoMotor.setText("Apagado");
        }
        if(vehiculo.getEstadoViaje()==Vehiculo.ESTADO_NORMAL){
            lEstadoViaje.setText("Normal"); 
        }else if(vehiculo.getEstadoViaje()==Vehiculo.ESTADO_DETENIDO){
            lEstadoViaje.setText("Detenido");
        }else if(vehiculo.getEstadoViaje()==Vehiculo.ESTADO_PATINANDO){
            lEstadoViaje.setText("Patinando");
        }else{
            lEstadoViaje.setText("Accidentado");
        }     
    }
    
    public void manejarExcepciones(Exception e){
        taMensaje.setText(e.getMessage());
    }
    
    public void manejarExcepciones(String e){
        taMensaje.setText(e);
    }
    

    @Override
    public void actualizar() {
        actualizarLabels();
    }
}
